/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jwstudio_ndkdemo_CCallJava */

#ifndef _Included_com_jwstudio_ndkdemo_CCallJava
#define _Included_com_jwstudio_ndkdemo_CCallJava

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jwstudio_ndkdemo_CCallJava
 * Method:    callbackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jwstudio_ndkdemo_CCallJava_callbackAdd
  (JNIEnv *, jobject);

/*
 * Class:     com_jwstudio_ndkdemo_CCallJava
 * Method:    callbackHelloFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jwstudio_ndkdemo_CCallJava_callbackHelloFromJava
  (JNIEnv *, jobject);

/*
 * Class:     com_jwstudio_ndkdemo_CCallJava
 * Method:    callbackPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jwstudio_ndkdemo_CCallJava_callbackPrintString
  (JNIEnv *, jobject);

/*
 * Class:     com_jwstudio_ndkdemo_CCallJava
 * Method:    callbackSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jwstudio_ndkdemo_CCallJava_callbackSayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
