/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jwstudio_ndkdemo_JavaCallC */

#ifndef _Included_com_jwstudio_ndkdemo_JavaCallC
#define _Included_com_jwstudio_ndkdemo_JavaCallC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jwstudio_ndkdemo_JavaCallC
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jwstudio_ndkdemo_JavaCallC_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jwstudio_ndkdemo_JavaCallC
 * Method:    stringConcatenation
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jwstudio_ndkdemo_JavaCallC_stringConcatenation
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jwstudio_ndkdemo_JavaCallC
 * Method:    increaseArrayElements
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_jwstudio_ndkdemo_JavaCallC_increaseArrayElements
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_jwstudio_ndkdemo_JavaCallC
 * Method:    greeting
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jwstudio_ndkdemo_JavaCallC_greeting
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
